CATEGORIES: dict = {
    'Одежда и обувь': 'fashion',
    'Продукты питания': 'food',
    'Кафе и рестораны': 'food',
    'Медицина': 'health',
    'Авто': 'vehicle',
    'Спорт': 'sports',
    'Развлечения': 'entertainment',
    'АЗС': 'fuel',
    'Кино': 'cinema',
    'Питомцы': 'pets',
    'Книги': 'books',
    'Цветы': 'flowers',
    'Едим дома': 'onlineservices',
    'Смотрим дома': 'onlineservices',
    'Играем дома': 'onlineservices',
    'Косметика и Парфюмерия': 'premiumgoods',
    'Подарки': 'gifts',
    'Ремонт дома': 'homerepair',
    'Мебель': 'furniture',
    'Спа и массаж': 'wellness',
    'Ювелирные украшения': 'premiumgoods',
    'Такси': 'transport',
    'Отели': 'travel',
    'Путешествия': 'travel'
}